name: Create PR from token-update to main

on:
  push:
    branches:
      - token-update
  workflow_dispatch:

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "🔄 Update Tokens from Figma"
          title: "💄 Neue Token-Änderungen"
          body: |
            Automatischer Pull Request aus `token-update`, nachdem neue Tokens gepusht wurden.
          base: main
          head: token-update
          branch: token-update
          delete-branch: false
